package it.cascino.dbsqlite;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DEPOSITI".
*/
public class DepositiDao extends AbstractDao<Depositi, Long> {

    public static final String TABLENAME = "DEPOSITI";

    /**
     * Properties of entity Depositi.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Iddep = new Property(1, String.class, "iddep", false, "IDDEP");
        public final static Property Desc = new Property(2, String.class, "desc", false, "DESC");
    }


    public DepositiDao(DaoConfig config) {
        super(config);
    }
    
    public DepositiDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DEPOSITI\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"IDDEP\" TEXT NOT NULL ," + // 1: iddep
                "\"DESC\" TEXT NOT NULL );"); // 2: desc
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DEPOSITI\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Depositi entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getIddep());
        stmt.bindString(3, entity.getDesc());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Depositi entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getIddep());
        stmt.bindString(3, entity.getDesc());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Depositi readEntity(Cursor cursor, int offset) {
        Depositi entity = new Depositi( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // iddep
            cursor.getString(offset + 2) // desc
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Depositi entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setIddep(cursor.getString(offset + 1));
        entity.setDesc(cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Depositi entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Depositi entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Depositi entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
