package it.cascino.dbsqlite;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "BARCODE".
 */
@Entity
public class Barcode {

    @Id(autoincrement = true)
    private Long id;

    @NotNull
    private String codice;
    private Float tipo;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Barcode() {
    }

    public Barcode(Long id) {
        this.id = id;
    }

    @Generated
    public Barcode(Long id, String codice, Float tipo) {
        this.id = id;
        this.codice = codice;
        this.tipo = tipo;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getCodice() {
        return codice;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCodice(@NotNull String codice) {
        this.codice = codice;
    }

    public Float getTipo() {
        return tipo;
    }

    public void setTipo(Float tipo) {
        this.tipo = tipo;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
