package it.cascino.dbsqlite;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "BARCODE".
 */
public class BarcodeDao extends AbstractDao<Barcode, Long>{

	public static final String TABLENAME = "BARCODE";

	/**
	 * Properties of entity Barcode.<br/>
	 * Can be used for QueryBuilder and for referencing column names.
	 */
	public static class Properties{
		public final static Property Id = new Property(0, Long.class, "id", true, "_id");
		public final static Property Codice = new Property(1, String.class, "codice", false, "CODICE");
		public final static Property Tipo = new Property(2, Float.class, "tipo", false, "TIPO");
	}


	public BarcodeDao(DaoConfig config){
		super(config);
	}

	public BarcodeDao(DaoConfig config, DaoSession daoSession){
		super(config, daoSession);
	}

	/**
	 * Creates the underlying database table.
	 */
	public static void createTable(Database db, boolean ifNotExists){
		String constraint = ifNotExists ? "IF NOT EXISTS " : "";
		db.execSQL("CREATE TABLE " + constraint + "\"BARCODE\" (" + //
				"\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
				"\"CODICE\" TEXT NOT NULL ," + // 1: codice
				"\"TIPO\" REAL);"); // 2: tipo
	}

	/**
	 * Drops the underlying database table.
	 */
	public static void dropTable(Database db, boolean ifExists){
		String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BARCODE\"";
		db.execSQL(sql);
	}

	@Override
	protected final void bindValues(DatabaseStatement stmt, Barcode entity){
		stmt.clearBindings();

		Long id = entity.getId();
		if(id != null){
			stmt.bindLong(1, id);
		}
		stmt.bindString(2, entity.getCodice());

		Float tipo = entity.getTipo();
		if(tipo != null){
			stmt.bindDouble(3, tipo);
		}
	}

	@Override
	protected final void bindValues(SQLiteStatement stmt, Barcode entity){
		stmt.clearBindings();

		Long id = entity.getId();
		if(id != null){
			stmt.bindLong(1, id);
		}
		stmt.bindString(2, entity.getCodice());

		Float tipo = entity.getTipo();
		if(tipo != null){
			stmt.bindDouble(3, tipo);
		}
	}

	@Override
	public Long readKey(Cursor cursor, int offset){
		return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
	}

	@Override
	public Barcode readEntity(Cursor cursor, int offset){
		Barcode entity = new Barcode( //
				cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
				cursor.getString(offset + 1), // codice
				cursor.isNull(offset + 2) ? null : cursor.getFloat(offset + 2) // tipo
		);
		return entity;
	}

	@Override
	public void readEntity(Cursor cursor, Barcode entity, int offset){
		entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
		entity.setCodice(cursor.getString(offset + 1));
		entity.setTipo(cursor.isNull(offset + 2) ? null : cursor.getFloat(offset + 2));
	}

	@Override
	protected final Long updateKeyAfterInsert(Barcode entity, long rowId){
		entity.setId(rowId);
		return rowId;
	}

	@Override
	public Long getKey(Barcode entity){
		if(entity != null){
			return entity.getId();
		}else{
			return null;
		}
	}

	@Override
	public boolean hasKey(Barcode entity){
		return entity.getId() != null;
	}

	@Override
	protected final boolean isEntityUpdateable(){
		return true;
	}

}
