package it.cascino.dbsqlite;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "INFOGENERICHE".
 */
@Entity
public class Infogeneriche {

    @Id(autoincrement = true)
    private Long id;

    @NotNull
    private String info;

    @NotNull
    private String valore;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Infogeneriche() {
    }

    public Infogeneriche(Long id) {
        this.id = id;
    }

    @Generated
    public Infogeneriche(Long id, String info, String valore) {
        this.id = id;
        this.info = info;
        this.valore = valore;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getInfo() {
        return info;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setInfo(@NotNull String info) {
        this.info = info;
    }

    @NotNull
    public String getValore() {
        return valore;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setValore(@NotNull String valore) {
        this.valore = valore;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
